services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "0926881013"
      POSTGRES_DB: ecommerce
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data # 資料持久化，重要！

volumes:
  postgres_data: # 定義一個名為 postgres_data 的空間存資料